### ISSUE TITLE
[Q] Rabbitmq-connector on kubernetes deployment "panic runtime error"

### ISSUE THREAD

**Issue by shivupoojar** [Templum/rabbitmq-connector#312]
Hi
I am deploying the rabbitmq-connector on K8s cluster running on VMs with AMD processors, but getting following error:
2023/02/15 13:18:45 maxprocs: Updating GOMAXPROCS=2: determined from CPU quota
2023/02/15 13:18:45 OpenFaaS RabbitMQ Connector [Version: v1.0.8 Commit: a9e3668]
2023/02/15 13:18:45 Will read basic64 secret from path /etc/openfaas which was set via 'secret_mount_path'
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x6e2535]

goroutine 1 [running]:
github.com/Templum/rabbitmq-connector/pkg/config.getTopology({0x7fa540, 0xa7d7e8})
        /go/src/github.com/Templum/rabbitmq-connector/pkg/config/config.go:212 +0x95
github.com/Templum/rabbitmq-connector/pkg/config.NewConfig({0x7fa540, 0xa7d7e8})
        /go/src/github.com/Templum/rabbitmq-connector/pkg/config/config.go:75 +0x2ee
main.main()
        /go/src/github.com/Templum/rabbitmq-connector/main.go:40 +0x270

**Comment by shivupoojar** [comment]
I could figure it out, my configuration were wrong
